name: Claude Review Bot

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Claude Code GitHub Integration
        uses: nicholastlee119/claude-code-github-action@0.1.1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
